/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed-variant": "#5a4300",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d5e3fc",
        "primary-fixed-dim": "#adc7ff",
        "surface-container": "#eceef0",
        "tertiary": "#755800",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface-variant": "#414754",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fefcff",
        "on-background": "#191c1e",
        "background": "#f7f9fb",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "surface-bright": "#f7f9fb",
        "primary-container": "#0070ea",
        "surface-container-low": "#f2f4f6",
        "surface-dim": "#d8dadc",
        "primary": "#0059bb",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#b9c7df",
        "on-secondary-fixed": "#0d1c2e",
        "surface-tint": "#005bc0",
        "tertiary-container": "#936f00",
        "on-primary": "#ffffff",
        "surface": "#f7f9fb",
        "error": "#ba1a1a",
        "outline-variant": "#c1c6d7",
        "on-secondary-fixed-variant": "#3a485b",
        "on-error": "#ffffff",
        "secondary": "#515f74",
        "outline": "#717786",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#f7be1d",
        "tertiary-fixed": "#ffdf9a",
        "on-tertiary-fixed": "#251a00",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed": "#001a41",
        "inverse-surface": "#2d3133",
        "secondary-container": "#d5e3fc",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#004493",
        "on-secondary-container": "#57657a",
        "inverse-primary": "#adc7ff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
